name: 01-Building-Blocks
on: workflow_dispatch
jobs:
  echo-Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
  echo-Goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: passing Step
        run: |
          echo "I will pass with exit code 0"
          exit 0
      - name: Say Goodbye
        run: echo "Goodbye!"